Выполнена верстка макета "Закрывающий тег"
palameda/zakrivayuschiy-teg pull request #1
Opened 2024-02-09 07:44 UTC by palameda

Анимация (бесконечная) стрелки в меню без проблем работает в chromium подобных браузерах, но плохо работает в firefox. Там она отображается только при выборе тёмной темы, при переключения в режим авто или на светлую тему стрелка пропадает. При этом, если перевести браузер в режим разработчика (F12), то стрелка появляется.
Версия браузера Mozilla Firefox 122.0.1, ОС Linux Mint последней редакции.

2024-02-09 10:01 UTC, Savallera requested changes
## Здравствуйте! У Вас хорошая работа, что отметила 


### Положительные моменты:

* Все комментарии в коде с пометкой **Отлично**.
* Проект размещен на GitHub Pages
* Нет ошибок валидации, а также отсутствуют ошибки в консоли
* Корректно работают цветовые темы
* Изображения не искажаются и выглядят как в брифе.
* Верстка по Pixel Perfect
* При сужении экрана не образуется горизонтальный скролл.


### Что требует доработки:

* Все комментарии в коде с пометкой **Надо исправить** 

### Что можно сделать лучше:

* Все комментарии в коде с пометкой **Можно лучше**
* Для всех функций  `var()`  в CSS нужно задать резервные значения,  на случай если доступ к кастомному свойству по имени будет невозможен. Подробнее https://doka.guide/css/custom-properties/
* [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/)



    Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены, основные требования соответствуют брифу и чек листу. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

    Комментарии **Надо исправить** обязательны для исправления, работа будет зачтена после исправления всех таких комментариев.
    Комментарии **Можно лучше** носят рекомендательный характер, их выполнение остается на ваше усмотрение. 


**У Вас все получится! Удачного дня!**

2024-02-12 16:59 UTC, palameda commented on styles/variables.css
> +    --accent-font: 'Press Start 2P', sans-serif;
Перечитал задание. Не встретил упоминание о fantasy. В макете только Inter и Press Start 2P

2024-02-12 17:00 UTC, palameda commented on fonts/fonts.css
> +    font-family: 'Inter Variable';
Шрифты были даны в заготовке. С ними ничего не делал.

2024-02-12 17:11 UTC, palameda commented on styles/style.css
> +.page::after {
Наверное не понял, но по макету так и должно быть. Без .page::after исчезнет белый/чёрный фон.

2024-02-12 17:55 UTC, palameda commented on index.html
> +    <link rel="icon" href="./svg/favicon.svg" type="image/svg+xml" />
Фавиконка непобедима. Попробовал два вариант: цвет в виде кода и передать его с помощью переменной, к сожалению, не успех
```
 path {
        fill: --main-color;
      }
      @media (prefers-color-scheme: dark) {
        path {
          fill: --main-color;
        }
      }
```

2024-02-12 18:05 UTC, palameda commented on styles/style.css
> +.theme-menu__item:has(.theme-menu__button:disabled)::before {
Спасибо. Справедливое замечание, но очень хочется оставить 😊

2024-02-12 18:19 UTC, palameda commented
Спасибо за ревью. Получил полезные знания в попытке внести правки. Удалось отработать большую часть замечаний, остальные буду прорабатывать в рамках следующего проекта.

2024-02-13 09:51 UTC, Savallera requested changes
### Здравствуйте! Спасибо, что уделили внимание комментариям и внесли исправления.

Хорошая работа по замечаниям, отметила моменты, которые требуют еще доработки, работа засчитывается на второй итерации.

**Что требует доработки:**

* Все комментарии в коде с пометкой **Надо исправить**
* Некоторые комментарии с первого ревью.

--- 

Комментарии **Надо исправить** обязательны для исправления.

У Вас все получится! Желаю Вам успехов во всех начинаниях.

2024-02-13 09:51 UTC, Savallera commented on svg/favicon.svg
> +        fill: --main-color;
**Надо исправить**
Скорректируйте сво-во цвета, не используя переменную, а точный цвет hex #000000


https://yadi.sk/d/o-lwyb-rDXOxzA например так

2024-02-13 09:51 UTC, Savallera commented on styles/variables.css
> +  --accent-font: "Press Start 2P", sans-serif;
**Надо исправить** Скорректируйте альтернативный шрифт по заданию - fantasy

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +.page::after {
Вы поняли макет буквально, он в этом плане похож на работу Сложно сосредоточиться, где фоновая картинка фиксируется и при скролле прокручивается вместе с прокруткой. Чтобы этого добиться псевдоэлемент тут лишний

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +  transition: opacity 0.3s linear;
**Надо исправить** Скорректируйте функцию проигрывания по заданию `ease`

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +  transition: transform 0.3s linear;
**Надо исправить** Скорректируйте функцию проигрывания по заданию `ease`

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +.theme-menu__item:has(.theme-menu__button:disabled)::before {
В таком случае могу предложить оформить стрелочку не у элемента списка `.theme-menu__item::before`, а у интерактивной кнопки `.theme-menu__button::before {}`. Таким образом когда кнопка будет неактивна слеектор можно будет описать проще `.theme-menu__button:disabled::before {}`

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +  transition: border-color 0.3s linear;
**Надо исправить** Скорректируйте функцию проигрывания по заданию `ease`

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +
**Надо исправить** Не хватает описание контура `.like-icon .contour {}`

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +  transition: box-shadow 0.3s linear;
**Надо исправить** Скорректируйте функцию проигрывания по заданию `ease`

`linear` только у контуров сердечка

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +  transition: transform 0.5s linear;
**Надо исправить** Скорректируйте функцию проигрывания по заданию `ease`

2024-02-13 09:51 UTC, Savallera commented on styles/style.css
> +  transition: color 1s linear;
**Надо исправить** Скорректируйте функцию проигрывания по заданию `ease`

2024-02-13 10:36 UTC, merged